name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'

      - name: Install Dependencies
        run: |
          make python_dependencies
          make ruby_dependencies

      - name: Lint
        run: |
          black --check ./python/
          rubocop ./ruby

      - name: Run Tests
        run: |
          pytest ./python/
          cd ruby; rake

      - name: Run Go Tests
        run: |
          for dir in ./go/*/; do
            (cd "$dir" && go test ./...)
          done
